from fastapi import FastAPI
from fastapi.responses import JSONResponse
from pydantic import BaseModel
import os

app = FastAPI()

class TicketRequest(BaseModel):
    incident_file: str
    team: str = "RIT"

@app.post("/ticket")
async def create_ticket(request_data: TicketRequest):
    """Create Linear ticket - simplified version without external dependencies"""
    try:
        # Get Linear API key from environment
        linear_api_key = os.getenv("LINEAR_API_KEY")
        
        if not linear_api_key:
            # No API key - return informative mock ticket
            return {
                "status": "success",
                "ticket_id": "RIT-MOCK-001",
                "ticket_url": "https://linear.app/ritwik-vats/issue/RIT-MOCK-001",
                "type": "mock",
                "message": "Mock ticket created - Add LINEAR_API_KEY to Vercel environment for real tickets"
            }
        
        # Try to import requests - if it fails, return mock
        try:
            import requests
        except ImportError:
            return {
                "status": "success",
                "ticket_id": "RIT-MOCK-002",
                "ticket_url": "https://linear.app/ritwik-vats/issue/RIT-MOCK-002",
                "type": "mock",
                "message": "Mock ticket created - requests library not available in Vercel"
            }
        
        # Extract incident ID from request
        incident_id = request_data.incident_file.split('/')[-1].replace('.json', '') if '/' in request_data.incident_file else request_data.incident_file.replace('.json', '')
        
        # Create incident data based on incident ID
        incident_data = {
            "TCK-1001": {
                "title": "Checkout intermittently timing out",
                "service": "orders-api",
                "error": "CheckoutTimeoutError: payment gateway exceeded 5s"
            },
            "TCK-1002": {
                "title": "Refund limits not enforced for premium users", 
                "service": "payments-api",
                "error": "RefundLimitExceededError: Missing tier config"
            },
            "TCK-1003": {
                "title": "Authentication rate limiting bypassed",
                "service": "auth-api", 
                "error": "LoginRateLimitError: Too many attempts"
            }
        }.get(incident_id, {
            "title": "Unknown incident",
            "service": "unknown",
            "error": "Unknown error"
        })
        
        # GraphQL mutation for Linear
        mutation = """
        mutation IssueCreate($input: IssueCreateInput!) {
            issueCreate(input: $input) {
                success
                issue {
                    id
                    identifier
                    url
                }
            }
        }
        """
        
        # Map team keys to actual Linear team IDs
        team_mapping = {
            "RIT": "bda83a58-5164-4f3c-8d99-eafb7e7deb72",  # Ritwik_Space team ID
            "FTS": "bda83a58-5164-4f3c-8d99-eafb7e7deb72"   # Default to same team
        }
        
        team_id = team_mapping.get(request_data.team, "bda83a58-5164-4f3c-8d99-eafb7e7deb72")
        
        variables = {
            "input": {
                "title": f"[RCA] {incident_data['title']}",
                "description": f"**Incident:** {incident_id}\\n**Service:** {incident_data['service']}\\n**Error:** {incident_data['error']}\\n\\nGenerated by RCA Agent Dashboard",
                "teamId": team_id,
                "priority": 2
            }
        }
        
        # Make Linear API call with proper error handling
        try:
            response = requests.post(
                "https://api.linear.app/graphql",
                headers={
                    "Authorization": linear_api_key,  # Linear API key format
                    "Content-Type": "application/json",
                    "User-Agent": "RCA-Agent/1.0"
                },
                json={"query": mutation, "variables": variables},
                timeout=30  # Increased timeout for Vercel
            )
        except requests.exceptions.RequestException as e:
            return {
                "status": "success",
                "ticket_id": "RIT-MOCK-006",
                "ticket_url": "https://linear.app/ritwik-vats/issue/RIT-MOCK-006",
                "type": "mock",
                "message": f"Mock ticket created - Network error: {str(e)[:100]}"
            }
        
        # Check response
        if response.status_code == 200:
            result = response.json()
            
            # Check for GraphQL errors
            if "errors" in result:
                error_msg = result["errors"][0].get("message", "Unknown GraphQL error")
                return {
                    "status": "success",
                    "ticket_id": "RIT-MOCK-003",
                    "ticket_url": "https://linear.app/ritwik-vats/issue/RIT-MOCK-003",
                    "type": "mock",
                    "message": f"Mock ticket created - Linear API error: {error_msg}"
                }
            
            # Check for successful issue creation
            if result.get("data", {}).get("issueCreate", {}).get("success"):
                issue = result["data"]["issueCreate"]["issue"]
                return {
                    "status": "success",
                    "ticket_id": issue["identifier"],
                    "ticket_url": issue["url"],
                    "type": "real",
                    "message": f"✅ Created real Linear ticket {issue['identifier']}"
                }
        
        # API call failed - return detailed mock
        return {
            "status": "success",
            "ticket_id": "RIT-MOCK-004",
            "ticket_url": "https://linear.app/ritwik-vats/issue/RIT-MOCK-004",
            "type": "mock",
            "message": f"Mock ticket created - Linear API returned {response.status_code}"
        }
            
    except Exception as e:
        # Detailed error handling
        return {
            "status": "success",
            "ticket_id": "RIT-MOCK-005",
            "ticket_url": "https://linear.app/ritwik-vats/issue/RIT-MOCK-005",
            "type": "mock",
            "message": f"Mock ticket created - Exception: {str(e)[:100]}"
        }

# This is the entry point for Vercel
from mangum import Mangum
handler = Mangum(app, lifespan="off")
